name = "Titus"
uuid = "161ade51-a71e-4c5f-b262-f1262fd3217d"
authors = ["Nathan-Wamsley"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Cthulhu = "f68482b8-f384-11e8-15f7-abe071a5a75f"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DemoCards = "311a05b2-6137-4a5a-b473-18580a3d38b5"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
GLMNet = "8d5ece8b-de18-5317-b113-243142960cc6"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
PDFmerger = "3beb2ed1-af7d-458f-b727-6e9beb3586c0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PrettyPrinting = "54e16d92-306c-5ea0-a30b-337be88ac337"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
Query = "1a8c2f83-1ff3-5112-b086-8aa67b057ba1"
RobustModels = "d6ea1423-9682-4bbd-952f-b1577cbf8c98"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
