name = "Pioneer"
uuid = "585db54e-1982-41c9-ae07-9e9eb56c7d61"
authors = ["Natahan Wamsley"]
version = "0.2.7"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
ArrowTypes = "31f734f8-188a-4ce0-8406-c8a06bd891cd"
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
EvoTrees = "f6006082-12f8-11e9-0c9c-0d5d367ab1e5"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
FASTX = "c2308a5c-f048-11e8-3e8a-31650f418d12"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
InlineStrings = "842dd82b-1e85-43dc-bf29-5d0ee9dffc48"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
NumericalIntegration = "e7bfaba1-d571-5449-8927-abc22e82249b"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SentinelArrays = "91c51154-3ec4-41a3-a24f-3f23e20d615c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
ArgParse = "1.2"
Arrow = "2.7"
ArrowTypes = "2.3"
CSV = "0.10"
CodecZlib = "0.7"
Combinatorics = "1.0"
DataFrames = "1.6"
DataStructures = "0.18"
Dictionaries = "0.4"
Distributions = "0.25"
EvoTrees = "0.17.3"
EzXML = "1"
FASTX = "2.1"
FastGaussQuadrature = "1"
GR = "0.73.13"
HTTP = "1.10.15"
InlineStrings = "1"
Interpolations = "0.15"
JLD2 = "0.5"
JSON = "0.21"
KernelDensity = "0.6"
LaTeXStrings = "1"
LightXML = "0.9"
LinearSolve = "2.31"
Logging = "1.11.0"
LoggingExtras = "1.1.0"
LoopVectorization = "0.12"
MLJModelInterface = "1.12.0"
Measures = "0.3"
NumericalIntegration = "0.2"
Optim = "1"
Plots = "1.40"
Polynomials = "4.0"
ProgressBars = "1.5"
SentinelArrays = "1"
SpecialFunctions = "2.4"
StaticArrays = "1.9"
StatsBase = "0.34"
StatsPlots = "0.15"
Tables = "1.12"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
